services:
  # Redis - Message broker for microservices
  redis:
    image: redis:7-alpine
    container_name: learn-monorepos-redis-dev
    ports:
      - '6379:6379'
    volumes:
      - redis_dev_data:/data
    networks:
      - microservices-dev
    command: redis-server --appendonly yes

  # User Service (Development)
  user-service:
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
      target: base
    container_name: learn-monorepos-user-service-dev
    volumes:
      - ./apps/user-service:/app/apps/user-service
      - ./libs:/app/libs
      - user_service_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - microservices-dev
    command: npx nx serve user-service

  # Order Service (Development)
  order-service:
    build:
      context: .
      dockerfile: apps/order-service/Dockerfile
      target: base
    container_name: learn-monorepos-order-service-dev
    volumes:
      - ./apps/order-service:/app/apps/order-service
      - ./libs:/app/libs
      - order_service_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    networks:
      - microservices-dev
    command: npx nx serve order-service

  # API Gateway (Development)
  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
      target: base
    container_name: learn-monorepos-api-gateway-dev
    ports:
      - '3000:3000'
    volumes:
      - ./apps/api-gateway:/app/apps/api-gateway
      - ./libs:/app/libs
      - api_gateway_node_modules:/app/node_modules
      - api_gateway_nx_cache:/tmp/nx
    environment:
      - NODE_ENV=development
      - PORT=3000
      - USER_SERVICE_HOST=user-service
      - ORDER_SERVICE_HOST=order-service
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NX_DAEMON=false
      - NX_CACHE_PROJECT_GRAPH=false
      - NX_SKIP_NX_CACHE=true
      - NX_CACHE_DIRECTORY=/tmp/nx
    depends_on:
      - redis
      - user-service
      - order-service
    networks:
      - microservices-dev
    command: npx nx serve api-gateway

networks:
  microservices-dev:
    driver: bridge

volumes:
  redis_dev_data:
    driver: local
  user_service_node_modules:
    driver: local
  order_service_node_modules:
    driver: local
  api_gateway_node_modules:
    driver: local
  api_gateway_nx_cache:
    driver: local
